# Generated by Django 4.2 on 2023-05-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_lecturenote_options_lecturenote_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturenote",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
